import 'small_question_item.dart';

enum QuestionCategory {
  forJhs(
    '中学向け学問',
    'assets/category_logo/image30.png',
  ),
  forHs(
    '高校向け学問',
    'assets/category_logo/image31.png',
  ),
  trivia(
    '雑学',
    'assets/category_logo/image32.png',
  ),
  topicsOfTheDay('時事問題', 'assets/category_logo/image33.png');

  const QuestionCategory(this.title, this.imagePath);
  final String title;
  final String imagePath;
}

final l = [
  SmallQuestionItem(
    id: 1,
    questionStatement: "lim[x→∞]sinx/xを求めよ。",
    choices: ["0", "1", "-∞", "∞"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "夏の大三角を構成するはくちょう座の一等星は何",
    choices: ["ベガ", "デネブ", "アルタイル", "シリウス"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "月の重力加速度として最も適切なものを答えよ",
    choices: ["1.6", "9.8", "29", "59"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "今年行われるサッカーW杯で日本とグループリーグでない国は？",
    choices: ["スペイン", "ニュージーランド", "コスタリカ", "ドイツ"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "y=logₐx について、真数条件及び底の条件を求めよ。",
    choices: ["a>0,x≠1", "a≠1,x>0", "a>0,0<x≠1", "0<a≠1,x>0"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "今年映画がまだ公開されていないアニメは？",
    choices: ["すずめの戸締まり", "コナン", "ミニオン", "ワンピース"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "スタバの今年の期間限定のフラペチーノでないものは？",
    choices: ["バナナナバナナ", "ザメロンオブメロン", "フルーツGYUNEW", "さくら咲いたベリー"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "今年神奈川で開かれる大会はなんでしょう？",
    choices: ["国民体育大会", "全国健康福祉祭", "万国博覧会", "国際園芸博覧会"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "大谷翔平が成した2桁勝利2桁ホームランは何年ぶりの偉業か？",
    choices: ["100", "104", "106", "107"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "映画トップガン・マーベリックで主人公が最後に乗った戦闘機は？",
    choices: ["F14", "F16", "F18", "F20"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "今年4月から成人が18になったが、できるようになったことは？",
    choices: ["車の運転", "国民年金", "国家資格の取得", "5年パスポートの取得"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "今年の金曜ロードショー「夏はジブリ」で放送されてないものは？",
    choices: ["天空の城ラピュタ", "耳をすませば", "となりのトトロ", "ハウルの動く城"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "新500円玉に使われている金属は？",
    choices: ["亜鉛", "鉄", "アルミニウム", "ニホニウム"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "今年JAXAを早期退職した元宇宙飛行士は誰？",
    choices: ["野口聡一さん", "山崎直子さん", "向井千秋さん", "秋山豊寛さん"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "コドンを明らかにしたのは誰か。",
    choices: ["デモクリトス", "シュワン", "ニーレンバーグ", "ワトソン"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "本校スーパーアドバイザー小林誠先生が受賞された賞は何？",
    choices: ["ノーベル経済学賞", "ノーベル物理学賞", "ノーベル化学賞", "ノーベル平和賞"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "本校に植えられている、学術誌natureより寄贈された木は？",
    choices: ["月桂樹", "椿", "レッドロビン", "みかん"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "本校の住所は横浜市鶴見区小野町〇です。〇に入る数字は？",
    choices: ["4", "5", "6", "7"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "開校してから今日まで、PTAだよりは何号まで発行されている？",
    choices: ["27", "29", "31", "33"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "本校の校歌を作詞・作曲されたオオゼキタクさんのデビュー曲は？",
    choices: ["群青グラフィティ", "レモン", "恋オーラ", "START"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "一般的なギターの弦は何本？",
    choices: ["4", "5", "6", "8"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "エアコンを省略せずに言うと何？",
    choices: ["エアコンプリート", "エアコントローラー", "エアコング", "エアコンディショナー"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "車道が左側通行の国はどの国？",
    choices: ["アメリカ", "ドイツ", "マレーシア", "ベトナム"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "マレーシアを漢字1文字で表すとどの漢字になる？",
    choices: ["麻", "磨", "真", "馬"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "赤本を出版しているのはどこの会社？",
    choices: ["旺文社", "ベネッセ", "集英社", "数学社"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "焼肉のミノとはどこの部位？",
    choices: ["腎臓", "胃", "膵臓", "脾臓"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "神奈川県に市はいくつある？",
    choices: ["13", "16", "19", "22"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "焼き鳥のハツとはどこの部分？",
    choices: ["心臓", "肺", "舌", "脳"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "ライオンは何科の動物？",
    choices: ["ライオン科", "ネコ科", "ヒョウ科", "イヌ科"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "縄跳びの技で実際にあるのは？",
    choices: ["はやぶさ", "飛行機", "フライングダイナソー", "ペガサス"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "日本初の鉄道が走ったのは新橋とどこの駅の間？",
    choices: ["渋谷", "浅草", "桜木町", "鶴見小野"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "今現在、日本で1番高いビルはどれ？",
    choices: ["ランドマークタワー", "六本木ヒルズ", "あべのハルカス", "ブルジュ・ハリファ"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "桜木町に昨年オープンしたロープウェイの名前は？",
    choices: ["ヨコハマエアキャビン", "Airヨコハマ", "cu-mo横浜", "空YOKOHAMA"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "ベイスターズの親会社、DeNAのゲームは次のうちどれ？",
    choices: ["原神", "ウマ娘", "ファミコン", "エイペックス"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "ベクトル𝔸,𝔹が一次独立している条件に不適なのはどれか。",
    choices: ["𝔸≠ゼロベクトル", "𝔹≠ゼロベクトル", "|𝔸|≠|𝔹|", "𝔸∦𝔹"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "漢文においてすなわチと読める漢字として不適切なものを選べ。",
    choices: ["乃", "輒", "須", "則"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "フランスの国旗の３色が表していないものは？",
    choices: ["平和", "自由", "平等", "博愛"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "大谷翔平が104年ぶりに達成したのは誰の記録？",
    choices: ["ソト", "ラミレス", "ダルビッシュ有", "ベーブ・ルース"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "∫1/cos²x dxを求めよ。",
    choices: ["1/tanx", "-1/tanx", "tanx", "-tanx"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "このなかで合弁花類であるものはなにか？",
    choices: ["エンドウ", "サクラ", "ヒマワリ", "アブラナ"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "AgBrの色は何色でしょうか。",
    choices: ["赤褐色", "白色", "淡黄色", "黒紫色"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "2020オリンピックの日本の金メダルの数",
    choices: ["27", "24", "17", "14"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "名探偵コナンハロウィンの花嫁のスペシャルゲストキャラの出身地",
    choices: ["アメリカ", "イギリス", "ロシア", "スウェーデン"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "約束のネバーランドとほぼ同時に完結したJUMP作品は？",
    choices: ["銀魂", "食戟のソーマ", "チェンソーマン", "約束のネバーランド"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "ONEPIECE REDのウタの歌を担当した人は？",
    choices: ["Ado", "あるふぁきゅん", "96猫", "鹿乃"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "ワンピース RED で機材トラブルの時映っていたキャラは",
    choices: ["ウソップ", "サンジ", "ゾロ", "チョッパー"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "今年実写化されるジブリ作品は？",
    choices: ["思い出のマーニー", "風立ちぬ", "千と千尋の神隠し", "耳をすませば"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "現在の横浜市の人口は？",
    choices: ["約3.7万人", "約37万人", "約370万人", "約3700万人"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "2番目に狭い都道府県はどこ？",
    choices: ["東京都", "神奈川県", "大阪府", "沖縄県"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "2番目に広い都道府県はどこ？",
    choices: ["岩手県", "長野県", "福島県", "新潟県"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "食欲をそそると言われている色は？",
    choices: ["赤", "青", "紫", "白"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "日本で1番多い苗字は？",
    choices: ["田中", "高橋", "鈴木", "佐藤"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "2021年の1世帯あたりの餃子の購入額1位の都市はどこ？",
    choices: ["盛岡市", "宇都宮市", "浜松市", "宮崎市"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "この中で最大収容人数が1番多いのはどこ？",
    choices: ["日本武道館", "有明アリーナ", "横浜アリーナ", "ぴあアリーナMM"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "次の都市のうち政令指定都市であるものはどれ？",
    choices: ["佐賀市", "長崎市", "熊本市", "鹿児島市"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "琵琶湖は滋賀県の面積のどれくらいを占めているでしょう？",
    choices: ["約1/2", "約1/4", "約1/6", "約1/8"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "2022年の箱根駅伝、優勝したのは何大学？",
    choices: ["駒澤大学", "青山学院大学", "東海大学", "日本体育大学"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "今年の夏の甲子園、優勝したのはどこの高校？",
    choices: ["大阪桐蔭高校", "近江高校", "下関国際高校", "仙台育英高校"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "今年、冬季オリンピックが開催されたのはどこの国？",
    choices: ["カナダ", "中国", "ノルウェー", "オーストリア"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "大河ドラマ｢鎌倉殿の十三人｣で小栗旬さんが演じる主人公は誰？",
    choices: ["源頼朝", "源義朝", "北条義時", "北条泰時"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "環境温度によって胚の性別が決まる動物は次のうちどれ？",
    choices: ["ハクビシン", "キタキツネ", "カモノハシ", "ワニガメ"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "動物細胞に無いものはどれ？",
    choices: ["細胞膜", "細胞壁", "核膜", "核膜孔"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "東京ディズニーシーは昨年、オープン何周年を迎えたでしょう？",
    choices: ["15周年", "20周年", "25周年", "30周年"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "ヨードホルム反応で検出出来ない有機化合物を選べ。",
    choices: ["エタノール", "アセトン", "酢酸", "2-プロパノール"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "昆虫類が呼吸をしている部分はどこか？",
    choices: ["頭部", "胸部", "腹部", "あし"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "水上置換法で集められないきたいはどれか？",
    choices: ["水素", "酸素", "二酸化炭素", "アンモニア"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "2つの力が釣り合う条件として正しくないのはどれか？",
    choices: ["２力が一直線上にある", "２力の向きが反対", "作用点が同じ", "２力の大きさが等しい"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "助動詞「べし」の意味として不適切なものを選べ。",
    choices: ["推量", "意志", "仮定", "当然"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "y=aˣ と y=logₐx はどの直線を軸に対称か。",
    choices: ["x軸", "y軸", "y=x", "y=-x"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "役目が実力に対し軽いことを○不足という。○の漢字の画数は？",
    choices: ["2", "3", "6", "7"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "1ラジアンは度数法で何度か。",
    choices: ["(180/π)°", "(360/π)°", "(π/180)°", "(π/360)°"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "2022年7月9日、イーロン・マスクが買収を辞めたのは何社？",
    choices: ["Twitter", "Instagram", "YouTube", "zenly"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "2022年7月23日、WHOが緊急事態と発表した病気は？",
    choices: ["COVID19", "サル痘", "インフルエンザ", "りんご病"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "f'(a)=lim[h→ア]f(a+h)-f(a)/h-イ",
    choices: ["ア→0,イ→0", "ア→0,イ→a", "ア→a,イ→0", "ア→a,イ→a"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "内陸国でない国は？",
    choices: ["スイス", "ブルガリア", "モンゴル", "カザフスタン"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "双子葉類の特徴の組み合わせとして正しいものは？",
    choices: ["ひげ根-平行脈", "ひげ根-綱状脈", "主根と側根-平行脈", "主根と側根-綱状脈"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "以下のハロゲン化水素のうち最も沸点が低いものを選べ。",
    choices: ["HF", "HCl", "HBr", "HI"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "甲殻類でないものはどれか？",
    choices: ["ザリガニ", "ダンゴムシ", "ミジンコ", "ウニ"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "金属の共通の性質として正しくないのはどれか？",
    choices: ["磁石につく", "磨くと金属光沢が出る", "天性と延性がある", "電気を通し熱を伝える"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "この中で一番高い音が出る弦はどれか？",
    choices: ["長さ10㎝太さ1㎜", "長さ10㎝太さ2㎜", "長さ20㎝太さ1㎜", "長さ20㎝太さ2㎜"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "地球で最も大きい大陸は？",
    choices: ["アフリカ大陸", "南極大陸", "北アフリカ大陸", "ユーラシア大陸"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "世界で面積の大きさが４位内に入らない国は？",
    choices: ["ロシア", "アメリカ", "ブラジル", "カナダ"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "次の中で裸子植物なのはどれか？",
    choices: ["ウメ", "ナズナ", "イチョウ", "タンポポ"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "A+B→ABについて反応速度式はv=k[A]ˣ[B]ʸである",
    choices: ["x=0,y=1", "x=1,y=0", "x=1,y=1", "x,yは分からない"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "この中で軟体動物ではないのはどれか？",
    choices: ["クラゲ", "アサリ", "イカ", "タニシ"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "メスシリンダーの液体の測り方で正しくないのはどれか。",
    choices: ["最小目盛りを読み取る", "真横から見る", "一番低い部分を見る", "水平面に置く"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "レンズを通して見える虚像の説明として正しくないのはどれか？",
    choices: ["物体が焦点より内側", "向きが物体と同じ", "実物より大きい", "スクリーンにうつる"],
    correctAnswerIndex: 4,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "詔勅の読み方は？",
    choices: ["しょうとく", "しょうちょく", "とうとく", "とうちょく"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "x=5はx²=25であるための必要条件か、十分条件か。",
    choices: ["必要条件", "十分条件", "必要十分条件", "どちらでもない"],
    correctAnswerIndex: 1,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "2022年7月2日に起こった大規模通信障害はどの会社が原因？",
    choices: ["ソフトバンク", "au", "docomo", "楽天モバイル"],
    correctAnswerIndex: 2,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "空気の量が適切な炎の色はどれか？",
    choices: ["うすい赤", "黄色", "うすい青色", "無色"],
    correctAnswerIndex: 3,
  ),
  SmallQuestionItem(
    id: 1,
    questionStatement: "光源ではないものはどれか？",
    choices: ["太陽", "電灯", "燃えてるろうそく", "月"],
    correctAnswerIndex: 4,
  ),
];
